### PR TITLE
ICMP Patch

### PR DESCRIPTION
**Pull request by alevere**
Add additional support for ICMP per request of Univ of Oslo.
Require that src/dst are of same ip version.
Remove requirement of rule_number for slpf:Target
Added ability to send error when ports are specified for a protocol that doesnt use ports

### CODE REVIEW

**Comment by jmbrule** [comment]
I Have preference for introducing an ICMP target or overload the ipv*_connection target rather than create an argument.  Introducing an ICMP Type argument seems a bit like a kluge to me....
Thoughts?

**Comment by sparrell** [comment]
My preference for handling ICMP (and any other protocols other than tcp/udp) that we define the 5 tuple to handle all cases:

- Proto= TCP - 5 tuple is proto=TCP, src-ip, dst-ip, src-port, dest-port
- Proto= UDP - 5 tuple is proto=UDP, src-ip, dst-ip, src-port, dest-port
- Proto= ICMP - 5 tuple is proto=ICMP, src-ip, dst-ip, icmp-type, icmp-code
- Proto= any other - 5 tuple is proto, src-ip, dst-ip, unused, unused

I believe there is precedent for this in industry, albeit old, in netflowV5.

I agree a more 'modern' way to do it might be to just define each protocol as it's own target which is how many of today's firewalls do it at the user interface, but they all translate the English words to the numbers in the protocol/etc fields so I maintain that they are doing the proposal above under the hood.

**Comment by alevere** [comment]
I wrote the pull request, but I could go either way. Take a look, but right now it is written as a new slpf:Target.

It would kind of mean making the 5 tuple a 6 tuple, with the last part being ICMP specific.
e.g.
protocol
src
dest
srcport
destport
type (optional and must be null unless protocol=1)

It doesnt scale for other protocols, but I do feel that ICMP is a special case, as it was written into TCP/IP from the start to handle messaging and errors.

-Alex
________________________________

**Comment by alevere** [comment]
Duncan:

I think for that we would need to go back to the lang spec group (same with adding 6th ID called icmp type), and create a few tables that are based on the l4 protocol and have different names for different protocols. Not that I am against it, I think there are at least 3 valid ways to do this.

[cid:8372eede-01da-4589-a2d5-1a0ab151d795]
________________________________

**Comment by sparrell** [comment]
@alevere - agree (speaking both as sfractal and as LSC cochair) fully that it should go to LSC.

**Pull request closed without merging**
