### PR TITLE
Slpf 26 create more conformance profiles

### PR DESCRIPTION
**Pull request by jmbrule**

### CODE REVIEW

**Comment by dlemire60** [comment]
For consistency with other discussions, "openc2 producers" and "openc2 consumers" should be "Producers" and "Consumers", respectively. Agreement on L-Spec was that since they are defined terms they should be initial cap ([LS issue 214](https://github.com/oasis-tcs/openc2-oc2ls/issues/214)).

Grammar of the opening sentence of 3.1.1 is suspect; suggest "An Producer conforming to Baseline OpenC2 Producer:".  This might require 3.1.1.2 to be rewritten to start with "MUST ..." A similar comment applies to the way _all_ of the conformance clause introductions are worded. Also, currently all have the same typo:  "statisifes"should be "satisfies"

There are a few instances of "Conformnace", which should be "Conformance ".

Why do we need both 3.1.1.3 and 3.1.1.4?

Should 3.1.1.5 and 3.1.16 say Version 1 or higher of the L-Spec?

All of the above comments for 3.1.1 also apply to the peer items in 3.1.2.

The sample messages look OK to me, but the opinion of implementers should outweigh mine.

**Comment by jmbrule** [comment]
In response to why do we need BOTH 3.1.1.3 AND 3.1.1.4:  They are different conformance criteria.  
3.1.1.3 states your firewall can be conformant provided it supports the transfer of hte commands.  3.1.1.4 states it must support one of the published OpenC2 transfer specs.  
I did not want to create a situation where a product is not conformant because it does not support HTTPS.

**Comment by jmbrule** [comment]
In the context of 'grammar is suspect'.  It is almost an exact paste of taken from OASIS.  Take a look at section 5.2 of http://docs.oasis-open.org/templates/TCHandbook/ConformanceGuidelines.html 
Well, they spelled satisfies correctly, but otherwise....

**Comment by jmbrule** [comment]
Per agreement on Feb 13 2019 AP-SC meeting

**Pull request merged**
